### PR TITLE
Work in progress: Use optimized Deferred and update DS methods for latest Waterline.

### PR DESCRIPTION
**Pull request by mikermcneil**
### Examples

```js
sails.getDatastore('foo')
.leaseConnection(function (db, proceed){
  //...
  var exactly24HoursAgo = Date.now() - 1000*60*60*24;

  User.find({ createdAt: {'>': exactly24HoursAgo } })
  .limit(150)
  .sort('createdAt DESC')
  .usingConnection(db)
  .exec(function(err, recentNewUsers) {
    if (err) { return proceed(err); }

    Sales.count({ createdAt: {'>': exactly24HoursAgo } })
    .usingConnection(db).exec(function(err, numNewSales) {
      if (err) { return proceed(err); }

      return proceed(undefined,{
        newUsers: recentNewUsers,
        numNewSales: numNewSales
      });
    });

  });
})
.exec(function (err, engagementReport) {
  // ...
});
```

And finally, here's a quick test of transactions that you can copy and paste into the Sails REPL:
```js
// Assuming you have a User model with a `luckyNumber` attribute which has
// the `unique: true` constraint...
User.getDatastore().transaction(function(db, proceed){  async.map(require('lodash').range(10), function (i, next){  var rand = Math.floor(Math.random()*10);  User.findOrCreate({luckyNumber: rand}, {luckyNumber: rand }).usingConnection(db).meta({fetch: true}).exec(next); }, proceed);  }).exec(function _afterwards(){if (arguments[0]) { console.log('ERROR:', arguments[0]); return; } console.log('Ok.  Result:',arguments[1]);  });

//^^^ should result in an error-- and when examining the state of the database afterwards,
//    nothing should have been created.  (Contrast this behavior with the same code, but
//    replacing "transaction" with "leaseConnection".  Without the transaction, some records
//    would be created, but the transaction prevents this from happening)
```

### Status

**Update: As of Jan 27, all four methods are good to go, and this PR is ready to merge.**

(Still, read on if you want to check out some ideas about how this might be expanded going forward.)

~~Warning: This is not ready to merge yet as of Jan 26: I'm still working on the other RDI methods.  I'm just opening the PR now so that it's easy to find for the purpose of cloning it down to try out dynamic connection leasing from app-level code.~~

> ### Caveat
> 
> There are good arguments to be made about why the proposal below should be defined as a separate method instead of `getDatastore()`, and even better arguments to be made about why this should instead just take the form of a single generic method like `leaseOneOffConnection(during).exec(afterwards)` (i.e. you need a dynamic manager, not really a connection.  At least in every conceivable case I can think of...)
>
> But anyway, the only real _technical_ hurdle w/ the exact usage below is that the manager cannot be created synchronously.  So _something_ would have to change.
>
>
> ##### Original proposal
>
> Note that datastores are still static at the moment.  **In the future**, it wouldn't be much work at all to support top-level usage more or less like:
> ```js
> sails.getDatastore({
>   adapter: 'sails-mysql',
>   url: 'mysql://user@some-misc.com/db'
> })
> .leaseConnection(function (db, proceed){
>   //...
>   return proceed();
> })
> .exec(function (err, resultMaybe) {
>   // ...
> });
> ```
>
>
> ^^That would allow you to use datastore methods to easily build things like your own custom phpMyAdmin, etc., where datastores are dynamic (i.e. not known ahead-of-time on lift / when you configure your config/datastores.js file)

### CODE REVIEW

**Comment by mikermcneil** [comment]
To sum up the above proposal for future usage-- one simple way to fix the problems discussed in "caveat" would just be to do it like this:

```js
sails.leaseDynamicConnection({
  adapter: require('sails-mysql'),
  url: 'mysql://user@some-misc.com/db'
}, function (db, proceed){
  //...
  return proceed();
})
.exec(function (err, resultMaybe) {
  // ...
});
```

^^That takes care of all of the main issues I brought up above with only one extra generic method, and it still lets you do all of the same things.

> The only other related issue is that, if we want to allow running transactions on dynamic datastores, then we'd either need to add a second generic method (e.g. `sails.runDynamicTransaction()` -OR- make the `transaction()` RDI method support `.usingConnection()`.  I think that if it turns out to be important, adding the second method would be a better idea.

**Comment by luislobo** [comment]
Wow. Congratulations!

**Comment by luislobo** [comment]
@mikermcneil 
I'm re reading these comments, I love the new way of doing things.
As we talked some other times, it would be great that the db object can have a `switchDatabase` method, that would allow to have multi tenant apps, that share the same connection, that way you don't have to actually reconnect using `leaseDynamicConnection`

**Comment by mikermcneil** [comment]
@luislobo :+1: down for getting to where we can do that at some point.  For datastores, I think you'd really need a hot manager (i.e. pool) switcher -- but I think there's some downsides to that too (it's nice to have datastores all ready to go at the beginning, since it's been easier to optimize the runtime performance of the methods.)  Of course, for models, you can already do this on a per-query basis by chaining on `.usingConnection()`. 

The way to do something like that down is probably just to take the ORM offline temporarily (temporarily queue any incoming queries and wait for already-started ones and their lifecycle callbacks to finish) then do a reload and fire everything back up.

**Pull request merged**
